### PR TITLE
Require search text in input field to submit form

### LINKED ISSUE #60: Empty search returns an empty page
**Describe the bug**
When you search with no text, you get taken to the search results page, but nothing displays.

**Expected behavior**
Either a message on the search results page telling the user to make a proper search, a list of all resource records, or something else.

### PR DESCRIPTION
**Pull request by p-galligan**
Requires text in the search field to submit a search.

Fixes #60

### CODE REVIEW

**Comment by helrond** [comment]
This works, but I think we should wait for @HaSistrunk's input before merging. Accessible forms are a whole thing, and we may need to add additional ARIA attributes to indicate a field has an error.

**Comment by p-galligan** [comment]
Bumping this for @HaSistrunk to see if she has thoughts on accessibility re: required field input.

**Comment by HaSistrunk** [comment]
@p-galligan , sorry for the delay! Accessibilty-wise, this causes the screenreader to announce that this text field is required, which is fine. However, there is no mechanism by which it is required for any users. Like if you try to submit a search with no text it still submits, right?

**Comment by p-galligan** [comment]
On my local build, it creates a pop up and stops submission. That's what the `required` after `aria-required=true` is doing.

Screen Shot 2020-09-14 at 11 21 46 AM

**Comment by HaSistrunk** [comment]
My bad, I had the wrong branch pulled up. Looks good to me.

**Review by HaSistrunk — APPROVED** [review]

**Comment by p-galligan** [comment]
@helrond going to go ahead and merge.

**Pull request merged**
