### PR TITLE
Add layouts and includes for single item display and home page

### LINKED ISSUE #10: Create single item display
**Describe the solution you'd like**
Display title, author name(s), call numbers, publication date, subjects and relevant notes (variant titles, etc.) in item display

**Additional context**
Detail

### LINKED ISSUE #23: Create includes for full item display
**Is your feature request related to a problem? Please describe.**
We need to build pages before we can build the site, and that involves creating includes for essential data elements. This could be split up into separate issues if necessary. 

**Describe the solution you'd like**
Create includes for full item display as laid out by [template](https://github.com/RockefellerArchiveCenter/library_discovery/issues/10). 

- Title
- Call Number
- Notes
- Subjects
- Dates
- Agents

### LINKED ISSUE #37: Create home page
**Describe the solution you'd like**
Add layouts and includes (if necessary) for home page.

### PR DESCRIPTION
**Pull request by helrond**
Started working on some templating and...one thing led to another:
- Adds layout and includes for single-item display, fixes #10 and fixes #23 
- Adds layout and includes for home page, fixes #37

### CODE REVIEW

**Comment by p-galligan** [comment]
Looks like the 404 page generation breaks the header and footer. Not sure exactly what's causing it though.
Screen Shot 2020-08-24 at 10 58 54 AM

**Review by p-galligan — CHANGES_REQUESTED** [review]
Happy to merge as is for now, but the 404 page is stumping me since it's being generated when built.

**Comment by helrond** [comment]
@p-galligan I can take a look at the 404 page. Likely it just needs some additional wrapper divs.

**Comment by helrond** [comment]
@p-galligan ready for your review

**Review by p-galligan — APPROVED** [review]

**Pull request merged**
