### PR TITLE
Add site wide includes (header, footer, head)

### LINKED ISSUE #29: Add universal site-wide includes.
**Is your feature request related to a problem? Please describe.**
Set up universal site-wide includes:

- header
- footer
- icons
- anything else as it comes up

**Describe the solution you'd like**
Set up `html` files for these sections on a page. May need to include a general `index.html` as well.

### PR DESCRIPTION
**Pull request by p-galligan**
Adds very basic site wide includes. These are almost exactly the same as the Docs site header and footer with some very minor changes.

Not sure what else we really need to include on these right now.

Fixes #29

### CODE REVIEW

**Review by helrond — CHANGES_REQUESTED** [review]
A couple of things:
- Based on the wireframes, I'd say a search bar would be a useful include to create.
- I believe that "standard RAC footer" was intended to refer more to something like the footer on rockarch.org (@HaSistrunk please jump in if I'm wrong!)
- Can we dispense with the minima theme because we're using our own custom templates? This would allow us to shed some gems.

**Comment by HaSistrunk** [comment]
> * I believe that "standard RAC footer" was intended to refer more to something like the footer on rockarch.org (@HaSistrunk please jump in if I'm wrong!)

Yeah, that's what I was thinking. In general I was thinking about starting to move toward consistency across our web properties for basic things like this as we look ahead to creating a design system/style guide. Not to jump the gun, though. Whatever makes sense for this project right now.

**Comment by p-galligan** [comment]
Ok, I've added a really basic search include as a placeholder for now.

I've removed the minima theme.

I've added basically the exact same footer for from rockarch.org. Only thing I'd like to call out is that the fonts in the footer for the social icons don't seem to be working right now, which I've confirmed with @HaSistrunk to be also happening in local DIMES-TNG builds. Any thoughts on this one?

**Comment by helrond** [comment]
The social icons aren't loading because fontawesome isn't loaded in DIMES-TNG (or this site). IMO we should probably find a better solution for this eventually - it seems dumb to load all that stuff for three icons...

**Review by helrond — APPROVED** [review]

**Pull request merged**
